import { useEffect, useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { Edit3, Plus, Trash2, X } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { db } from '../db/database';
import { uid } from '../utils/id';
import type { Client } from '../types/models';
import { Card, EmptyState, PageHeader, ProgressBar } from '../components/ui';

export function ClientsPage(){
  const clients=useLiveQuery(()=>db.clients.toArray(),[])??[];const videos=useLiveQuery(()=>db.videos.toArray(),[])??[];
  const [params,setParams]=useSearchParams();const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Client|null>(null);
  useEffect(()=>{if(params.get('add')==='1'){setOpen(true);setParams({}, {replace:true})}},[params,setParams]);
  return <div className="page"><PageHeader eyebrow="短视频运营 · 客户档案" title="客户" subtitle="合作信息、账号定位、周期和约定视频量都放进一个长期档案。" action={<button className="icon-btn" onClick={()=>setOpen(true)} aria-label="添加客户"><Plus size={20}/></button>}/><div className="stack">{clients.length?clients.map(c=>{const vs=videos.filter(v=>v.clientId===c.id);const done=vs.filter(v=>v.status==='已发布').length;return <Card key={c.id}><div className="row between start"><div className="grow"><div className="row"><div className="client-logo">{c.name.slice(0,2)}</div><div><div className="row"><h2>{c.name}</h2><span className="badge primary">{c.status}</span></div><div className="subtle tiny">{c.platform} · {c.account||'未填账号'} · {c.positioning||'未填定位'}</div></div></div><div className="row between client-progress-label"><strong>{done} / {c.promisedVideos}</strong><span className="subtle tiny">已发布 / 约定视频</span></div><ProgressBar value={done/Math.max(1,c.promisedVideos)*100}/><div className="client-meta">{c.ownerName&&<span>联系人 {c.ownerName}</span>}{c.startDate&&<span>{c.startDate} 开始</span>}{c.endDate&&<span>{c.endDate} 结束</span>}</div></div><button className="icon-btn small-icon" onClick={()=>setEditing(c)} aria-label="编辑客户"><Edit3 size={16}/></button></div></Card>}):<EmptyState title="还没有客户" text="添加客户后，就能跟踪视频数量与制作进度。" action={<button className="btn primary" onClick={()=>setOpen(true)}>添加客户</button>}/>}</div>{(open||editing)&&<ClientForm client={editing} onClose={()=>{setOpen(false);setEditing(null)}}/>}</div>
}

function ClientForm({client,onClose}:{client:Client|null;onClose:()=>void}){
  const [name,setName]=useState(client?.name||'');const [owner,setOwner]=useState(client?.ownerName||'');const [phone,setPhone]=useState(client?.phone||'');const [platform,setPlatform]=useState(client?.platform||'抖音');const [account,setAccount]=useState(client?.account||'');const [positioning,setPositioning]=useState(client?.positioning||'');const [count,setCount]=useState(client?.promisedVideos||20);const [startDate,setStartDate]=useState(client?.startDate||'');const [endDate,setEndDate]=useState(client?.endDate||'');const [status,setStatus]=useState<Client['status']>(client?.status||'合作中');const [notes,setNotes]=useState(client?.notes||'');
  const save=async()=>{if(!name.trim())return;const now=new Date().toISOString();const data={name:name.trim(),ownerName:owner.trim()||undefined,phone:phone.trim()||undefined,platform,account:account.trim()||undefined,positioning:positioning.trim()||undefined,promisedVideos:Math.max(1,count),startDate:startDate||undefined,endDate:endDate||undefined,status,notes:notes.trim()||undefined,updatedAt:now};if(client)await db.clients.update(client.id,data);else await db.clients.add({id:uid(),...data,createdAt:now});onClose()};
  return <div className="overlay" onMouseDown={onClose}><div className="sheet" onMouseDown={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="row between"><div><h2>{client?'编辑客户':'添加客户'}</h2><div className="subtle tiny">把合作资料一次记全，以后不用反复找聊天记录。</div></div><button className="icon-btn" onClick={onClose}><X size={20}/></button></div><div className="stack form-stack"><div className="field"><label>客户名称 *</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div><div className="grid two"><div className="field"><label>老板 / 联系人</label><input className="input" value={owner} onChange={e=>setOwner(e.target.value)}/></div><div className="field"><label>联系电话</label><input className="input" value={phone} onChange={e=>setPhone(e.target.value)}/></div></div><div className="grid two"><div className="field"><label>平台</label><select className="select" value={platform} onChange={e=>setPlatform(e.target.value)}><option>抖音</option><option>小红书</option><option>视频号</option><option>B站</option><option>其他</option></select></div><div className="field"><label>账号</label><input className="input" value={account} onChange={e=>setAccount(e.target.value)}/></div></div><div className="field"><label>账号定位</label><input className="input" value={positioning} onChange={e=>setPositioning(e.target.value)} placeholder="例如：燕郊租房 / 宠物医疗科普"/></div><div className="grid two"><div className="field"><label>约定视频数量</label><input className="input" type="number" min="1" value={count} onChange={e=>setCount(Number(e.target.value)||1)}/></div><div className="field"><label>合作状态</label><select className="select" value={status} onChange={e=>setStatus(e.target.value as Client['status'])}><option>合作中</option><option>暂停</option><option>已结束</option><option>归档</option></select></div></div><div className="grid two"><div className="field"><label>开始日期</label><input className="input" type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></div><div className="field"><label>结束日期</label><input className="input" type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></div></div><div className="field"><label>合作备注</label><textarea className="textarea" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="交付规则、客户偏好、禁区、重要沟通……"/></div>{client&&<button className="btn danger" onClick={async()=>{if(confirm('删除客户不会自动删除历史视频。确定继续吗？')){await db.clients.delete(client.id);onClose()}}}><Trash2 size={16}/>删除客户</button>}<button className="btn primary" disabled={!name.trim()} onClick={save}>保存客户</button></div></div></div>
}
