import { useNavigate } from 'react-router-dom';
import { useLiveQuery } from 'dexie-react-hooks';
import { BookOpenCheck, CircleHelp, NotebookTabs, ChartNoAxesColumnIncreasing } from 'lucide-react';
import { db } from '../db/database';
import { curriculum } from '../features/english/curriculum';
import { Card, PageHeader, ProgressBar, Section } from '../components/ui';
import { todayISO } from '../utils/date';

export function EnglishPage(){const nav=useNavigate();const today=todayISO();const records=useLiveQuery(()=>db.englishRecords.toArray(),[])??[];const todayRecords=records.filter(r=>r.date===today);const mins=todayRecords.reduce((s,r)=>s+r.minutes,0);const words=todayRecords.reduce((s,r)=>s+r.wordsLearned,0);return <div className="page"><PageHeader eyebrow="English Center" title="英语学习中心" subtitle="从零基础开始，一层一层把英语搭起来。"/><div className="grid two"><Card><div className="label">今日学习</div><div className="metric">{mins} min</div><ProgressBar value={mins/30*100}/></Card><Card><div className="label">今日单词</div><div className="metric">{words} / 30</div><ProgressBar value={words/30*100}/></Card></div><Section title="学习路线"><div className="stack">{curriculum.map(level=><Card key={level.id} className="level-card"><span className="level-num">{level.level}</span><div style={{position:'relative'}}><div className="eyebrow">LEVEL {level.level}</div><h2>{level.title}</h2><p className="subtle">{level.description}</p><div className="row between"><span className="badge">{level.units.reduce((s,u)=>s+u.lessons.length,0)} 节已内置</span>{level.units.length>0?<button className="btn small primary" onClick={()=>nav(`/english/lesson/${level.units[0].lessons[0].id}`)}>开始学习</button>:<span className="subtle">课程框架已预留</span>}</div></div></Card>)}</div></Section><Section title="专项工具"><div className="grid two">{[[BookOpenCheck,'课程练习','/english/lesson/l1-u1-1'],[CircleHelp,'错题本','/english/mistakes'],[NotebookTabs,'生词本','/english/vocabulary'],[ChartNoAxesColumnIncreasing,'学习统计','/english']].map(([Icon,title,path])=>{const I=Icon as typeof BookOpenCheck;return <button key={String(title)} onClick={()=>nav(String(path))} style={{border:0,padding:0,background:'transparent',textAlign:'left'}}><Card className="compact"><div className="row"><div className="icon-box primary"><I size={18}/></div><strong>{String(title)}</strong></div></Card></button>})}</div></Section></div>}
