import { useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { Plus, Trash2 } from 'lucide-react';
import { db } from '../db/database';
import { uid } from '../utils/id';
import { todayISO } from '../utils/date';
import { Card, PageHeader, ProgressBar, Section } from '../components/ui';

const cats=['餐饮','购物','交通','娱乐','学习','宠物','房租','生活','医疗','其他'];
export function FinancePage(){const expenses=useLiveQuery(()=>db.expenses.orderBy('date').reverse().toArray(),[])??[];const [amount,setAmount]=useState('');const [category,setCategory]=useState('餐饮');const [flow,setFlow]=useState<'支出'|'收入'>('支出');const [note,setNote]=useState('');const month=todayISO().slice(0,7);const monthRows=expenses.filter(e=>e.date.startsWith(month));const spend=monthRows.filter(e=>e.flow==='支出').reduce((s,e)=>s+e.amount,0);const income=monthRows.filter(e=>e.flow==='收入').reduce((s,e)=>s+e.amount,0);const budget=5000;const add=async()=>{const n=Number(amount);if(!n||n<=0)return;await db.expenses.add({id:uid(),amount:n,flow,category,account:'默认账户',date:todayISO(),note:note||undefined,createdAt:new Date().toISOString()});setAmount('');setNote('')};return <div className="page"><PageHeader title="记账" subtitle="先把钱记清楚，再慢慢看趋势。"/><div className="grid two"><Card><div className="label">本月支出</div><div className="metric">¥{spend.toFixed(0)}</div></Card><Card><div className="label">本月收入</div><div className="metric">¥{income.toFixed(0)}</div></Card></div><Section title="本月预算"><Card><div className="row between"><strong>¥{spend.toFixed(0)} / ¥{budget}</strong><span className={`badge ${spend>budget?'high':''}`}>{spend>budget?'已超支':`剩余 ¥${(budget-spend).toFixed(0)}`}</span></div><div style={{marginTop:10}}><ProgressBar value={spend/budget*100}/></div></Card></Section><Section title="记一笔"><Card><div className="tabs"><button className={`tab ${flow==='支出'?'active':''}`} onClick={()=>setFlow('支出')}>支出</button><button className={`tab ${flow==='收入'?'active':''}`} onClick={()=>setFlow('收入')}>收入</button></div><div className="grid two" style={{marginTop:12}}><div className="field"><label>金额</label><input className="input" type="number" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/></div><div className="field"><label>分类</label><select className="select" value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></div></div><div className="field" style={{marginTop:10}}><label>备注</label><input className="input" value={note} onChange={e=>setNote(e.target.value)} placeholder="可不填"/></div><button className="btn primary" style={{width:'100%',marginTop:12}} onClick={add}><Plus size={17}/>保存</button></Card></Section><Section title="最近账单"><Card>{expenses.slice(0,12).map(e=><div className="list-link" key={e.id}><div><strong>{e.category}</strong><div className="subtle" style={{fontSize:12}}>{e.date} · {e.note||e.account}</div></div><div className="row"><strong style={{color:e.flow==='支出'?'var(--text)':'var(--green)'}}>{e.flow==='支出'?'-':'+'}¥{e.amount.toFixed(2)}</strong><button className="btn ghost small" onClick={async()=>{if(confirm('删除这笔记录？'))await db.expenses.delete(e.id)}}><Trash2 size={15}/></button></div></div>)}</Card></Section></div>}
