import { useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { Plus, CheckSquare2, Trash2 } from 'lucide-react';
import { db } from '../db/database';
import { uid } from '../utils/id';
import { todayISO } from '../utils/date';
import { Card, EmptyState, PageHeader, Section } from '../components/ui';

export function NotesPage(){const memos=useLiveQuery(()=>db.memos.orderBy('updatedAt').reverse().toArray(),[])??[];const [title,setTitle]=useState('');const [content,setContent]=useState('');const add=async()=>{if(!title.trim()&&!content.trim())return;const now=new Date().toISOString();await db.memos.add({id:uid(),title:title.trim()||'未命名备忘录',content,category:'生活',checklist:[],createdAt:now,updatedAt:now});setTitle('');setContent('')};const toTask=async(id:string,title:string)=>{const cal=(await db.calendars.where('name').equals('生活').first())??await db.calendars.first();if(!cal)return;const now=new Date().toISOString();await db.tasks.add({id:uid(),title,calendarId:cal.id,category:'备忘录',tags:[],date:todayISO(),priority:'普通',status:'未开始',progress:0,subtasks:[],sourceType:'manual',sourceId:id,createdAt:now,updatedAt:now});alert('已转成今天的任务')};return <div className="page"><PageHeader title="备忘录" subtitle="先记下来，需要行动时再一键变成任务。"/><Card><div className="field"><label>标题</label><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：下周短视频选题"/></div><div className="field" style={{marginTop:10}}><label>内容</label><textarea className="textarea" value={content} onChange={e=>setContent(e.target.value)} placeholder="文字、清单思路、链接说明……"/></div><button className="btn primary" style={{width:'100%',marginTop:12}} onClick={add}><Plus size={17}/>保存备忘录</button></Card><Section title="最近记录"><div className="stack">{memos.length?memos.map(m=><Card key={m.id}><div className="row between start"><div style={{flex:1}}><div className="eyebrow">{m.category}</div><h2>{m.title}</h2><p className="subtle" style={{whiteSpace:'pre-wrap'}}>{m.content||'没有正文'}</p></div><button className="btn ghost small" onClick={async()=>{if(confirm(`删除“${m.title}”？`))await db.memos.delete(m.id)}}><Trash2 size={16}/></button></div><button className="btn small" onClick={()=>toTask(m.id,m.title)}><CheckSquare2 size={15}/>转成任务</button></Card>):<EmptyState title="还没有备忘录" text="灵感先落地，之后再整理。"/>}</div></Section></div>}
