import { useEffect, useMemo, useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { Edit3, FileUp, Plus, Trash2, X } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { db } from '../db/database';
import { uid } from '../utils/id';
import { ageText, daysBetween, todayISO } from '../utils/date';
import { fileToDataUrl, filesToAttachments } from '../utils/files';
import type { Attachment, Pet, PetRecord, PetRecordType } from '../types/models';
import { Card, EmptyState, PageHeader, Section } from '../components/ui';

const recordTypes:{type:PetRecordType;icon:string;label:string}[]=[
  {type:'疫苗',icon:'💉',label:'疫苗'},{type:'狂犬',icon:'🛡️',label:'狂犬'},{type:'驱虫',icon:'💊',label:'驱虫'},{type:'体检',icon:'🩺',label:'体检'},
  {type:'疾病',icon:'🤒',label:'生病'},{type:'体重',icon:'⚖️',label:'体重'},{type:'药物',icon:'🧴',label:'用药'},{type:'护理',icon:'🛁',label:'护理'},
  {type:'饮食',icon:'🥣',label:'饮食'},{type:'手术',icon:'🏥',label:'手术'},{type:'行为',icon:'🐾',label:'行为'},{type:'自定义',icon:'•••',label:'更多'}
];
const avatars=['🐈','🐱','🐈‍⬛','🐕','🐶','🐩','🐰','🐹','🦜','🐾'];

export function PetsPage(){
  const pets=useLiveQuery(()=>db.pets.toArray(),[])??[];
  const records=useLiveQuery(()=>db.petRecords.toArray(),[])??[];
  const [params,setParams]=useSearchParams();
  const [selectedId,setSelectedId]=useState<string>('');
  const [edit,setEdit]=useState<Pet|null>(null);const [add,setAdd]=useState(false);const [recordType,setRecordType]=useState<PetRecordType|null>(null);
  useEffect(()=>{if(!selectedId&&pets[0])setSelectedId(pets[0].id)},[pets,selectedId]);
  useEffect(()=>{if(params.get('record')==='1'&&pets[0]){setSelectedId(pets[0].id);setRecordType('自定义');setParams({}, {replace:true})}},[params,pets,setParams]);
  const pet=pets.find(p=>p.id===selectedId)??pets[0];
  const petRecords=useMemo(()=>records.filter(r=>r.petId===pet?.id).sort((a,b)=>b.date.localeCompare(a.date)),[records,pet]);
  const nextRecord=(type:PetRecordType)=>petRecords.filter(r=>r.type===type&&r.nextDate).sort((a,b)=>(a.nextDate||'').localeCompare(b.nextDate||''))[0];
  const weightRecords=petRecords.filter(r=>r.type==='体重'&&typeof r.value==='number').slice().reverse();
  return <div className="page"><PageHeader eyebrow="健康档案 · 预防计划 · 生活记录" title={pet?.name||'宠物中心'} subtitle="每只宠物都有独立主页：疫苗、狂犬、驱虫、疾病、用药、体重、护理和自定义记录都能长期保存。" action={<div className="top-actions">{pet&&<button className="icon-btn" onClick={()=>setEdit(pet)} aria-label="编辑宠物"><Edit3 size={18}/></button>}<button className="icon-btn" onClick={()=>setAdd(true)} aria-label="添加宠物"><Plus size={20}/></button></div>}/>
    {pets.length?<><div className="pet-tabs">{pets.map(p=><button className={`pet-chip ${p.id===pet?.id?'active':''}`} key={p.id} onClick={()=>setSelectedId(p.id)}><span>{p.photo?<img src={p.photo} alt=""/>:(p.avatar||'🐾')}</span>{p.name}</button>)}<button className="pet-chip" onClick={()=>setAdd(true)}><span>＋</span>添加宠物</button></div>
      {pet&&<><Card className="pet-hero"><div className="row start"><div className={`avatar big ${pet.photo?'pet-photo':''}`}>{pet.photo?<img src={pet.photo} alt={pet.name}/>:pet.avatar||'🐾'}</div><div className="grow"><div className="row between start"><div><b className="pet-name">{pet.name}</b><div className="subtle tiny">{pet.breed||pet.species} · {pet.sex||'未填性别'} · {pet.neutered?'已绝育':'未标记绝育'}</div></div><span className="badge done">档案正常</span></div><div className="grid three pet-stats"><div><b>{ageText(pet.birthday)}</b><span>年龄</span></div><div><b>{pet.weight?`${pet.weight}kg`:'未记录'}</b><span>当前体重</span></div><div><b>{pet.adoptionDate?`${Math.abs(daysBetween(pet.adoptionDate))}天`:'未填写'}</b><span>到家</span></div></div></div></div></Card>
      <Section title="健康状态" action={<button className="text-btn" onClick={()=>setRecordType('体检')}>＋ 体检记录</button>}><div className="health-grid">{([['疫苗','💉'],['狂犬','🛡️'],['驱虫','💊']] as const).map(([type,icon])=>{const r=nextRecord(type);const diff=r?.nextDate?daysBetween(r.nextDate):null;return <button className="health-item" key={type} onClick={()=>setRecordType(type)}><div className="hi">{icon}</div><b>{type}</b><span className={diff!==null&&diff<=7?'due':''}>{r?.nextDate?(diff!>=0?`下次 ${diff} 天`:`已逾期 ${Math.abs(diff!)} 天`):'暂无下次日期'}</span></button>})}</div></Section>
      <Section title="快速记录" action={<button className="text-btn" onClick={()=>setRecordType('自定义')}>自定义</button>}><div className="record-menu">{recordTypes.map(x=><button className="record-btn" key={x.type} onClick={()=>setRecordType(x.type)}><span>{x.icon}</span><span>{x.label}</span></button>)}</div></Section>
      <Section title="体重趋势" action={<button className="text-btn" onClick={()=>setRecordType('体重')}>＋ 记录</button>}><Card><div className="row between"><div><b className="weight-value">{pet.weight?`${pet.weight} kg`:'还没有体重'}</b><div className="subtle tiny">{weightRecords.length?`已经记录 ${weightRecords.length} 次`:'记录体重后会自动形成趋势'}</div></div>{pet.weight&&<span className="badge done">持续跟踪</span>}</div><WeightChart records={weightRecords}/></Card></Section>
      <Section title="健康时间线" action={<button className="text-btn" onClick={()=>setRecordType('自定义')}>＋ 新记录</button>}><Card>{petRecords.length?petRecords.slice(0,8).map(r=><div className="record-line" key={r.id}><div className="record-ico">{recordTypes.find(x=>x.type===r.type)?.icon||'📝'}</div><div><b className="small">{r.title}</b><div className="subtle tiny">{[r.type,r.hospital,r.doctor,r.nextDate?`下次 ${r.nextDate}`:''].filter(Boolean).join(' · ')}</div>{r.notes&&<div className="record-note">{r.notes}</div>}</div><span className="subtle tiny">{r.date.slice(5)}</span></div>):<div className="empty"><strong>还没有健康记录</strong><span>从疫苗、驱虫或体重开始记录。</span></div>}</Card></Section>
      </>}
    </>:<EmptyState title="还没有宠物档案" text="先添加一只宠物，再开始记录它的健康和生活。" action={<button className="btn primary" onClick={()=>setAdd(true)}>添加宠物</button>}/>} 
    {(add||edit)&&<PetForm pet={edit} onClose={()=>{setAdd(false);setEdit(null)}}/>}
    {recordType&&pet&&<PetRecordForm pet={pet} type={recordType} onClose={()=>setRecordType(null)}/>} 
  </div>
}

function PetForm({pet,onClose}:{pet:Pet|null;onClose:()=>void}){
  const [name,setName]=useState(pet?.name||'');const [species,setSpecies]=useState(pet?.species||'猫');const [breed,setBreed]=useState(pet?.breed||'');const [sex,setSex]=useState(pet?.sex||'');const [birthday,setBirthday]=useState(pet?.birthday||'');const [weight,setWeight]=useState(pet?.weight?String(pet.weight):'');const [adoption,setAdoption]=useState(pet?.adoptionDate||'');const [chip,setChip]=useState(pet?.chip||'');const [neutered,setNeutered]=useState(Boolean(pet?.neutered));const [avatar,setAvatar]=useState(pet?.avatar||'🐈');const [photo,setPhoto]=useState(pet?.photo||'');const [notes,setNotes]=useState(pet?.notes||'');
  const save=async()=>{if(!name.trim())return;const now=new Date().toISOString();const data={name:name.trim(),species,breed:breed.trim()||undefined,sex:sex||undefined,birthday:birthday||undefined,weight:weight?Number(weight):undefined,adoptionDate:adoption||undefined,chip:chip.trim()||undefined,neutered,avatar,photo:photo||undefined,notes:notes.trim()||undefined,updatedAt:now};if(pet)await db.pets.update(pet.id,data);else await db.pets.add({id:uid(),...data,createdAt:now});onClose()};
  return <div className="overlay" onMouseDown={onClose}><div className="sheet" onMouseDown={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="row between"><div><h2>{pet?'编辑宠物档案':'添加宠物'}</h2><div className="subtle tiny">头像可以选图标，也可以上传真实照片。</div></div><button className="icon-btn" onClick={onClose}><X size={20}/></button></div><div className="stack form-stack"><div className="field"><label>宠物头像</label><div className="avatar-picker">{avatars.map(x=><button className={`avatar-option ${avatar===x&&!photo?'selected':''}`} key={x} onClick={()=>{setAvatar(x);setPhoto('')}}>{x}</button>)}</div></div><label className="upload-zone"><FileUp size={20}/><span>上传宠物照片</span><input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)setPhoto(await fileToDataUrl(f))}}/></label>{photo&&<img className="pet-form-photo" src={photo} alt="宠物预览"/>}<div className="grid two"><div className="field"><label>名字 *</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label>种类</label><select className="select" value={species} onChange={e=>setSpecies(e.target.value)}><option>猫</option><option>狗</option><option>兔</option><option>鸟</option><option>仓鼠</option><option>其他</option></select></div></div><div className="grid two"><div className="field"><label>品种</label><input className="input" value={breed} onChange={e=>setBreed(e.target.value)} placeholder="英短"/></div><div className="field"><label>性别</label><select className="select" value={sex} onChange={e=>setSex(e.target.value)}><option value="">未填写</option><option>男生</option><option>女生</option></select></div></div><div className="grid two"><div className="field"><label>生日</label><input className="input" type="date" value={birthday} onChange={e=>setBirthday(e.target.value)}/></div><div className="field"><label>当前体重 kg</label><input className="input" type="number" step="0.1" value={weight} onChange={e=>setWeight(e.target.value)}/></div></div><div className="grid two"><div className="field"><label>到家日期</label><input className="input" type="date" value={adoption} onChange={e=>setAdoption(e.target.value)}/></div><div className="field"><label>芯片号</label><input className="input" value={chip} onChange={e=>setChip(e.target.value)}/></div></div><label className="toggle-row"><input type="checkbox" checked={neutered} onChange={e=>setNeutered(e.target.checked)}/><span>已绝育</span></label><div className="field"><label>备注</label><textarea className="textarea" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="性格、过敏、饮食偏好、长期注意事项……"/></div>{pet&&<button className="btn danger" onClick={async()=>{if(confirm(`删除 ${pet.name} 的档案？健康记录会保留，方便你先备份。`)){await db.pets.delete(pet.id);onClose()}}}><Trash2 size={16}/>删除宠物档案</button>}<button className="btn primary" disabled={!name.trim()} onClick={save}>保存宠物档案</button></div></div></div>
}

function PetRecordForm({pet,type,onClose}:{pet:Pet;type:PetRecordType;onClose:()=>void}){
  const [title,setTitle]=useState(defaultRecordTitle(type));const [date,setDate]=useState(todayISO());const [nextDate,setNextDate]=useState('');const [value,setValue]=useState(type==='体重'&&pet.weight?String(pet.weight):'');const [unit,setUnit]=useState(type==='体重'?'kg':'');const [hospital,setHospital]=useState('');const [doctor,setDoctor]=useState('');const [medicine,setMedicine]=useState('');const [dosage,setDosage]=useState('');const [notes,setNotes]=useState('');const [attachments,setAttachments]=useState<Attachment[]>([]);
  const save=async()=>{if(!title.trim())return;const rec:PetRecord={id:uid(),petId:pet.id,type,title:title.trim(),date,nextDate:nextDate||undefined,value:value?Number(value):undefined,unit:unit||undefined,hospital:hospital.trim()||undefined,doctor:doctor.trim()||undefined,medicine:medicine.trim()||undefined,dosage:dosage.trim()||undefined,notes:notes.trim()||undefined,attachments,createdAt:new Date().toISOString()};await db.petRecords.add(rec);if(type==='体重'&&value)await db.pets.update(pet.id,{weight:Number(value),updatedAt:new Date().toISOString()});onClose()};
  return <div className="overlay" onMouseDown={onClose}><div className="sheet" onMouseDown={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="row between"><div><h2>{recordTypes.find(x=>x.type===type)?.icon} 记录{type}</h2><div className="subtle tiny">{pet.name} · 可以上传化验单、疫苗本或现场照片</div></div><button className="icon-btn" onClick={onClose}><X size={20}/></button></div><div className="stack form-stack"><div className="field"><label>记录标题 *</label><input className="input" value={title} onChange={e=>setTitle(e.target.value)}/></div><div className="grid two"><div className="field"><label>日期</label><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="field"><label>下次日期</label><input className="input" type="date" value={nextDate} onChange={e=>setNextDate(e.target.value)}/></div></div>{type==='体重'&&<div className="grid two"><div className="field"><label>体重</label><input className="input" type="number" step="0.1" value={value} onChange={e=>setValue(e.target.value)}/></div><div className="field"><label>单位</label><input className="input" value={unit} onChange={e=>setUnit(e.target.value)}/></div></div>}{['药物','疾病','手术','驱虫','疫苗','狂犬'].includes(type)&&<div className="grid two"><div className="field"><label>药物 / 品牌</label><input className="input" value={medicine} onChange={e=>setMedicine(e.target.value)} placeholder="例如：大宠爱 / 妙三多"/></div><div className="field"><label>剂量</label><input className="input" value={dosage} onChange={e=>setDosage(e.target.value)} placeholder="例如：0.75ml"/></div></div>}<div className="grid two"><div className="field"><label>医院</label><input className="input" value={hospital} onChange={e=>setHospital(e.target.value)}/></div><div className="field"><label>医生</label><input className="input" value={doctor} onChange={e=>setDoctor(e.target.value)}/></div></div><label className="upload-zone"><FileUp size={20}/><span>上传图片 / 报告 / 文件</span><input type="file" multiple accept="image/*,.pdf" onChange={async e=>e.target.files&&setAttachments(await filesToAttachments(e.target.files))}/></label>{attachments.length>0&&<div className="attachment-list">{attachments.map(a=><span key={a.id}>{a.name}</span>)}</div>}<div className="field"><label>备注</label><textarea className="textarea" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="症状、反应、医生建议、护理注意事项……"/></div><button className="btn primary" disabled={!title.trim()} onClick={save}>保存记录</button></div></div></div>
}

function defaultRecordTitle(type:PetRecordType){if(type==='驱虫')return '体内外驱虫';if(type==='疫苗')return '疫苗接种';if(type==='狂犬')return '狂犬疫苗';if(type==='体重')return '体重记录';if(type==='体检')return '健康体检';return `${type}记录`}

function WeightChart({records}:{records:PetRecord[]}){
  const vals=records.map(r=>r.value!).filter(v=>Number.isFinite(v));
  if(vals.length<2)return <div className="weight-chart empty-chart">记录至少 2 次体重后，会在这里形成趋势曲线。</div>;
  const min=Math.min(...vals),max=Math.max(...vals);const range=Math.max(.1,max-min);const pts=vals.map((v,i)=>`${(i/(vals.length-1))*320},${76-((v-min)/range)*52}`).join(' ');
  return <div className="weight-chart"><svg viewBox="0 0 320 90" preserveAspectRatio="none"><polyline points={pts} fill="none" stroke="#6f82ef" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg></div>
}
