import { useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { Plus, Trash2 } from 'lucide-react';
import { db } from '../db/database';
import { uid } from '../utils/id';
import { todayISO } from '../utils/date';
import { Card, EmptyState, PageHeader, Section } from '../components/ui';

export function PetsPage(){const pets=useLiveQuery(()=>db.pets.toArray(),[])??[];const records=useLiveQuery(()=>db.petRecords.toArray(),[])??[];const [name,setName]=useState('');const [species,setSpecies]=useState('猫');const add=async()=>{if(!name.trim())return;const now=new Date().toISOString();await db.pets.add({id:uid(),name:name.trim(),species,createdAt:now,updatedAt:now});setName('')};const addRecord=async(id:string,petName:string)=>{const title=prompt(`给 ${petName} 添加记录，例如“体外驱虫”：`);if(!title)return;await db.petRecords.add({id:uid(),petId:id,type:'驱虫',title,date:todayISO(),createdAt:new Date().toISOString()})};return <div className="page"><PageHeader title="宠物中心" subtitle="把健康记录、体重和提醒放在同一个档案里。"/><Card><div className="grid two"><div className="field"><label>宠物名字</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="例如：团子"/></div><div className="field"><label>种类</label><input className="input" value={species} onChange={e=>setSpecies(e.target.value)}/></div></div><button className="btn primary" style={{width:'100%',marginTop:12}} onClick={add}><Plus size={17}/>添加宠物</button></Card><Section title="宠物档案"><div className="stack">{pets.length?pets.map(p=>{const rs=records.filter(r=>r.petId===p.id);return <Card key={p.id}><div className="row between start"><div><h2 style={{marginBottom:4}}>{p.name}</h2><div className="subtle">{p.species} {p.breed?`· ${p.breed}`:''} {p.weight?`· ${p.weight} kg`:''}</div><div className="row" style={{marginTop:10}}><span className="badge">{rs.length} 条记录</span>{rs[0]?.nextDate&&<span className="badge high">下次 {rs[0].nextDate}</span>}</div></div><button className="btn ghost small" onClick={async()=>{if(confirm(`删除 ${p.name} 的档案？`))await db.pets.delete(p.id)}}><Trash2 size={16}/></button></div><button className="btn small" style={{marginTop:12}} onClick={()=>addRecord(p.id,p.name)}>添加健康记录</button></Card>}):<EmptyState title="还没有宠物档案" text="添加后可以记录疫苗、驱虫、体重和生活事项。"/>}</div></Section></div>}
