import { useEffect, useMemo, useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { useSearchParams } from 'react-router-dom';
import { Edit3, Plus, Trash2, X } from 'lucide-react';
import { db } from '../db/database';
import { uid } from '../utils/id';
import type { Client, Video, VideoStatus } from '../types/models';
import { Card, EmptyState, PageHeader } from '../components/ui';
const statuses:VideoStatus[]=['选题','文案','待拍','已拍','剪辑','审核','待发布','已发布'];
export function VideosPage(){
  const [sp,setSp]=useSearchParams();const view=sp.get('view')==='kanban'?'kanban':'list';const statusFilter=sp.get('status') as VideoStatus|null;
  const videos=useLiveQuery(()=>db.videos.toArray(),[])??[];const clients=useLiveQuery(()=>db.clients.toArray(),[])??[];const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Video|null>(null);
  useEffect(()=>{if(sp.get('add')==='1'){setOpen(true);const p=new URLSearchParams(sp);p.delete('add');setSp(p,{replace:true})}},[sp,setSp]);
  const shown=useMemo(()=>statusFilter?videos.filter(v=>v.status===statusFilter):videos,[videos,statusFilter]);
  const updateStatus=(id:string,status:VideoStatus)=>db.videos.update(id,{status,updatedAt:new Date().toISOString()});
  return <div className="page"><PageHeader eyebrow="选题 → 文案 → 拍摄 → 剪辑 → 发布" title="视频项目" subtitle="每条视频都有完整档案，不只是一个状态标签。" action={<div className="top-actions"><button className="btn small" onClick={()=>setSp(view==='list'?{view:'kanban'}:{})}>{view==='list'?'看板':'列表'}</button><button className="icon-btn" onClick={()=>setOpen(true)} aria-label="添加视频"><Plus size={20}/></button></div>}/>{statusFilter&&<div className="filter-banner">正在查看：{statusFilter}<button onClick={()=>setSp({})}>清除筛选</button></div>}{view==='kanban'?<div className="section kanban">{statuses.map(status=><Card key={status} className="kanban-col"><div className="row between"><strong>{status}</strong><span className="badge">{videos.filter(v=>v.status===status).length}</span></div>{videos.filter(v=>v.status===status).map(v=><button className="kanban-card clean-button" key={v.id} onClick={()=>setEditing(v)}><strong>{v.title}</strong><div className="subtle tiny">{clients.find(c=>c.id===v.clientId)?.name||'未知客户'} · {v.contentType}</div><select className="select" value={v.status} onClick={e=>e.stopPropagation()} onChange={e=>updateStatus(v.id,e.target.value as VideoStatus)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></button>)}</Card>)}</div>:<div className="section stack">{shown.length?shown.slice().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(v=><Card key={v.id}><button className="video-detail-button clean-button" onClick={()=>setEditing(v)}><div className="row between start"><div className="grow"><div className="eyebrow">#{v.index} · {clients.find(c=>c.id===v.clientId)?.name||'未知客户'} · {v.contentType}</div><h2>{v.title}</h2><div className="subtle tiny">{v.topic||'未填写选题'} {v.publishDate?`· 计划 ${v.publishDate} 发布`:''}</div></div><Edit3 size={17}/></div></button><div className="video-status-row"><select className="select" value={v.status} onChange={e=>updateStatus(v.id,e.target.value as VideoStatus)}>{statuses.map(s=><option key={s}>{s}</option>)}</select>{typeof v.views==='number'&&<span className="badge">播放 {v.views}</span>}{typeof v.likes==='number'&&<span className="badge">赞 {v.likes}</span>}</div></Card>):<EmptyState title="还没有视频" text="先添加客户，再创建第一条视频。" action={<button className="btn primary" onClick={()=>setOpen(true)}>添加视频</button>}/>}</div>}{(open||editing)&&<VideoForm video={editing} clients={clients} existing={videos} onClose={()=>{setOpen(false);setEditing(null)}}/>}</div>
}

function VideoForm({video,clients,existing,onClose}:{video:Video|null;clients:Client[];existing:Video[];onClose:()=>void}){
 const [clientId,setClientId]=useState(video?.clientId||clients[0]?.id||'');const [title,setTitle]=useState(video?.title||'');const [topic,setTopic]=useState(video?.topic||'');const [copy,setCopy]=useState(video?.copy||'');const [script,setScript]=useState(video?.script||'');const [shootDate,setShootDate]=useState(video?.shootDate||'');const [publishDate,setPublishDate]=useState(video?.publishDate||'');const [platform,setPlatform]=useState(video?.platform||clients.find(c=>c.id===clientId)?.platform||'抖音');const [status,setStatus]=useState<VideoStatus>(video?.status||'选题');const [contentType,setContentType]=useState(video?.contentType||'其他');const [materialNotes,setMaterialNotes]=useState(video?.materialNotes||'');const [publishUrl,setPublishUrl]=useState(video?.publishUrl||'');const [views,setViews]=useState(video?.views?String(video.views):'');const [likes,setLikes]=useState(video?.likes?String(video.likes):'');
 const save=async()=>{if(!title.trim()||!clientId)return;const now=new Date().toISOString();const data={clientId,title:title.trim(),topic:topic.trim()||undefined,copy:copy.trim()||undefined,script:script.trim()||undefined,shootDate:shootDate||undefined,publishDate:publishDate||undefined,platform,status,contentType,materialNotes:materialNotes.trim()||undefined,publishUrl:publishUrl.trim()||undefined,views:views?Number(views):undefined,likes:likes?Number(likes):undefined,updatedAt:now};if(video)await db.videos.update(video.id,data);else await db.videos.add({id:uid(),index:existing.filter(v=>v.clientId===clientId).length+1,...data,createdAt:now});onClose()};
 return <div className="overlay" onMouseDown={onClose}><div className="sheet" onMouseDown={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="row between"><div><h2>{video?'编辑视频':'新建视频'}</h2><div className="subtle tiny">文案、脚本、拍摄、发布和数据都可以放在同一条记录里。</div></div><button className="icon-btn" onClick={onClose}><X size={20}/></button></div><div className="stack form-stack"><div className="field"><label>客户 *</label><select className="select" value={clientId} onChange={e=>setClientId(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>视频标题 *</label><input className="input" value={title} onChange={e=>setTitle(e.target.value)}/></div><div className="field"><label>选题</label><input className="input" value={topic} onChange={e=>setTopic(e.target.value)}/></div><div className="field"><label>文案</label><textarea className="textarea" value={copy} onChange={e=>setCopy(e.target.value)}/></div><div className="field"><label>拍摄脚本</label><textarea className="textarea" value={script} onChange={e=>setScript(e.target.value)}/></div><div className="grid two"><div className="field"><label>拍摄日期</label><input className="input" type="date" value={shootDate} onChange={e=>setShootDate(e.target.value)}/></div><div className="field"><label>发布日期</label><input className="input" type="date" value={publishDate} onChange={e=>setPublishDate(e.target.value)}/></div></div><div className="grid two"><div className="field"><label>状态</label><select className="select" value={status} onChange={e=>setStatus(e.target.value as VideoStatus)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="field"><label>内容类型</label><select className="select" value={contentType} onChange={e=>setContentType(e.target.value)}>{['科普','案例','剧情','活动','IP','产品','其他'].map(x=><option key={x}>{x}</option>)}</select></div></div><div className="field"><label>平台</label><input className="input" value={platform} onChange={e=>setPlatform(e.target.value)}/></div><div className="field"><label>素材备注</label><textarea className="textarea" value={materialNotes} onChange={e=>setMaterialNotes(e.target.value)}/></div><div className="field"><label>发布链接</label><input className="input" value={publishUrl} onChange={e=>setPublishUrl(e.target.value)}/></div><div className="grid two"><div className="field"><label>播放量</label><input className="input" type="number" value={views} onChange={e=>setViews(e.target.value)}/></div><div className="field"><label>点赞</label><input className="input" type="number" value={likes} onChange={e=>setLikes(e.target.value)}/></div></div>{video&&<button className="btn danger" onClick={async()=>{if(confirm(`删除“${video.title}”？`)){await db.videos.delete(video.id);onClose()}}}><Trash2 size={16}/>删除视频</button>}<button className="btn primary" disabled={!title.trim()||!clientId} onClick={save}>保存视频</button></div></div></div>
}
