import { useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { useSearchParams } from 'react-router-dom';
import { Plus, Trash2 } from 'lucide-react';
import { db } from '../db/database';
import { uid } from '../utils/id';
import type { VideoStatus } from '../types/models';
import { Card, EmptyState, PageHeader } from '../components/ui';
const statuses:VideoStatus[]=['选题','文案','待拍','已拍','剪辑','审核','待发布','已发布'];
export function VideosPage(){const [sp,setSp]=useSearchParams();const view=sp.get('view')==='kanban'?'kanban':'list';const videos=useLiveQuery(()=>db.videos.toArray(),[])??[];const clients=useLiveQuery(()=>db.clients.toArray(),[])??[];const [title,setTitle]=useState('');const [clientId,setClientId]=useState('');const add=async()=>{const cid=clientId||clients[0]?.id;if(!title.trim()||!cid)return;const now=new Date().toISOString();const index=videos.filter(v=>v.clientId===cid).length+1;await db.videos.add({id:uid(),clientId:cid,index,title:title.trim(),status:'选题',contentType:'其他',createdAt:now,updatedAt:now});setTitle('')};const updateStatus=(id:string,status:VideoStatus)=>db.videos.update(id,{status,updatedAt:new Date().toISOString()});return <div className="page"><PageHeader title="视频项目" subtitle="从选题到发布，每条视频都沿着同一条流水线前进。" action={<button className="btn small" onClick={()=>setSp(view==='list'?{view:'kanban'}:{})}>{view==='list'?'看板':'列表'}</button>}/><Card><div className="grid two"><div className="field"><label>视频标题</label><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：公寓拎包入住介绍"/></div><div className="field"><label>客户</label><select className="select" value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">默认客户</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div></div><button className="btn primary" style={{width:'100%',marginTop:12}} onClick={add}><Plus size={17}/>添加视频</button></Card>{view==='kanban'?<div className="section kanban">{statuses.map(status=><Card key={status} className="kanban-col"><div className="row between"><strong>{status}</strong><span className="badge">{videos.filter(v=>v.status===status).length}</span></div>{videos.filter(v=>v.status===status).map(v=><div className="kanban-card" key={v.id}><strong>{v.title}</strong><div className="subtle" style={{fontSize:12,margin:'5px 0 8px'}}>{clients.find(c=>c.id===v.clientId)?.name||'未知客户'}</div><select className="select" value={v.status} onChange={e=>updateStatus(v.id,e.target.value as VideoStatus)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>)}</Card>)}</div>:<div className="section stack">{videos.length?videos.sort((a,b)=>b.index-a.index).map(v=><Card key={v.id}><div className="row between start"><div style={{flex:1}}><div className="eyebrow">#{v.index} · {clients.find(c=>c.id===v.clientId)?.name||'未知客户'}</div><h2 style={{marginBottom:8}}>{v.title}</h2><select className="select" value={v.status} onChange={e=>updateStatus(v.id,e.target.value as VideoStatus)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><button className="btn ghost small" onClick={async()=>{if(confirm(`删除“${v.title}”？`))await db.videos.delete(v.id)}}><Trash2 size={16}/></button></div></Card>):<EmptyState title="还没有视频" text="先添加客户，再创建第一条视频。"/>}</div>}</div>}
